name: Build Binaries

on:
  push:
    paths:
      - 'Source/**'
  pull_request:
    paths:
      - 'Source/**'

jobs:
  build:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
      run: dotnet nuget locals all --clear
    - name: Build
      run: msbuild -m Source\Native\BuildAllTargets.proj
    - name: Prepare artifacts
      run: rm Source\Native\Output\Binaries\* -vb -Recurse -Force -Include *.exp, *.idb, *.ilk, *.iobj, *.ipdb, *.lastbuildstate, *.lib, *.obj, *.res, *.tlog
    - uses: actions/upload-artifact@v2
      with:
        name: NSudo_CI_Build
        path: Source\Native\Output\Binaries
